services:
  redis-stack:
    image: redis/redis-stack-server:latest
    container_name: redis-stack
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./docker/data:/data
    command: >
      redis-server --save "" --appendonly no
      --unixsocket /data/redis.sock --unixsocketperm 777
      --protected-mode no
      --loadmodule /opt/redis-stack/lib/redisearch.so
      --loadmodule /opt/redis-stack/lib/rejson.so
      --loadmodule /opt/redis-stack/lib/redistimeseries.so
      --loadmodule /opt/redis-stack/lib/redisbloom.so
    environment:
      # Path on the host where the socket will appear (bind-mounted ./docker/data)
      REDIS_SOCKET_PATH: ./docker/data/redis.sock
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -s /data/redis.sock ping || redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5